Minor fixes
IBM/wordpress-sample pull request #38
Opened 2018-01-14 14:02 UTC by kant

2018-01-15 13:13 UTC, loafyloaf requested changes
comments in-line

2018-01-15 13:13 UTC, loafyloaf commented on README.md
> +If you want to deploy the Wordpress directly to Bluemix, click on 'Deploy to Bluemix' button below to create a Bluemix DevOps service toolchain and pipeline for deploying the WordPress sample, else j
if we're getting specific, this should actually be 'WordPress'

2018-01-15 13:13 UTC, loafyloaf commented on README.md
> +After you modified the `wordpress-deployment.yaml`, run the following commands to deploy Wordpress.
ditto

2018-01-15 13:13 UTC, loafyloaf commented on README.md
>  kubectl get pods # Get the name of the wordpress pod
and once more

2018-01-16 00:09 UTC, jkomg approved these changes
LGTM

2018-08-03 12:19 UTC, closed without merging